2025/02/02 00:35:39 [error] 892#892: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.68.71.178, server: meapi.lagden.dev, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:40002/", host: "meapi.lagden.dev"
2025/02/02 00:35:42 [error] 895#895: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.70.240.56, server: meapi.lagden.dev, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:40002/", host: "meapi.lagden.dev"
2025/02/02 00:35:42 [error] 891#891: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.88.34, server: meapi.lagden.dev, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:40002/", host: "meapi.lagden.dev"
2025/02/02 00:35:43 [error] 892#892: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 162.158.39.136, server: meapi.lagden.dev, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:40002/", host: "meapi.lagden.dev"
